#!/bin/bash

source "`ueberzug library`"

# process substitution example:
ImageLayer 0< <(
    ImageLayer::add [identifier]="example0" [x]="0" [y]="0" [path]="~/r0hk31y7mtn31.jpg"
    ImageLayer::add [identifier]="example1" [x]="10" [y]="0" [path]="~/r0hk31y7mtn31.jpg"
    sleep 5
    ImageLayer::remove [identifier]="example0"
    sleep 5
)

