#!/usr/bin/env bash

source "`ueberzug library`"

#Y_AXIS=$(expr $(tput lines) / 4 )
X_AXIS=$(expr $(tput cols) / 4 )

for (( i=1; i<=$#; i++ ))
do
    clear
    {
    ImageLayer::add [identifier]="Image${i}" [x]=$X_AXIS [y]=0 [path]=${!i}
    read
    } | ImageLayer  
    
    #Y_AXIS=`expr $Y_AXIS + 10`

done
