#!/bin/bash

# Generate variables
ISO="$(ls /run/media/solarinas/Shelly/OS | fzf)"
qemu-img create -f qcow2 /run/media/solarinas/Tay/VMs/$1.qcow2 $2G



echo "qemu-system-x86_64 \
    -enable-kvm \
    -m 2G \
    -smp cores=4,threads=1,sockets=1,maxcpus=4 \
    -cpu host \
    -machine q35,accel=kvm \
    -cdrom /run/media/solarinas/Shelly/OS/$ISO \
    -usb -device usb-tablet\
    -drive file=/run/media/solarinas/Tay/VMs/$1.qcow2,format=qcow2,l2-cache-size=8M \
    -vga virtio \
    -display gtk" > ~/.VMs/$1
