#!/bin/bash

# Generate variables
ISO="$(ls /run/media/solarinas/Shelly/OS | fzf)"
SCRIPT_PATH=~/.local/bin

qemu-img create -f qcow2 /run/media/solarinas/Tay/VMs/$1.qcow2 $2G


echo "qemu-system-x86_64 \
    -enable-kvm \
    -m 2G \
    -smp cores=4,threads=1,sockets=1,maxcpus=4 \
    -cpu host \
    -machine q35,accel=kvm \
    -drive if=pflash,format=raw,readonly,file=/usr/share/ovmf/x64/OVMF_CODE.fd \
    -drive if=pflash,format=raw,file=/tmp/MY_VARS.fd \
    -cdrom /run/media/solarinas/Shelly/OS/$ISO \
    -usb -device usb-tablet\
    -drive file=/run/media/solarinas/Tay/VMs/$1.qcow2,format=qcow2,l2-cache-size=8M \
    -vga virtio \
    -display gtk" > $SCRIPT_PATH/$1
chmod +x $SCRIPT_PATH/$1
